### ISSUE TITLE
Errore "standard_init_linux.go:190 - windows 7

### ISSUE THREAD

**Issue by gianpaolot** [italia/spid-auth-docker#6]
Come richiesto apro una isssues su un problema che mi si è presentato, premetto era un ambiente di test in locale sulla mia macchina solo per studiare le configurazioni e il funzionamento.

Descrizione ambiente :
1. windows 7 Professional (Service pack 1)
2. docker toolbox

facendo il quickly test al run dell’applicazione mi rilancia sempre questo errore :

> "standard_init_linux.go:190: exec user process caused “no such file or directory”

**Comment by psmiraglia** [comment]
Ciao @gianpaolot , l'immagine docker non e' stata mai testata su Windows ma il problema (`no such file or directory`) e' abbastanza chiaro. Il demone Docker non riesce a trovare qualcosa.

Tieni presente che l'immagine e' stata sviluppata e pensata per sistemi Linux. Se vuoi farla girare su Windows, come prima cosa devi sistemare i path nei vari compose file.

Su Linux i path usano `/` (es. `/var/logs`), mentre su Windows `\` (`C:\Users\Alice`).

Altra cosa che subito mi salta all'occhio e' che in Windows non penso esistano i path indicati nel file `docker-compose.quickstart.yml`

https://github.com/italia/spid-auth-docker/blob/65a7a257c4f487f538d238c3bdb333d22e5030d0/docker-compose.quickstart.yml#L12-L14

Prova a fare queste modifiche e facci sapere.
