### ISSUE TITLE
Add spid custom error message

### ISSUE THREAD

**Issue by umbros** [italia/spid-auth-docker#7]
Is necessary to implement the management of SPID custom error codes:

ex:
<saml2p:Status>
        <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder"><saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:RequestUnsupported"/></saml2p:StatusCode>
        <saml2p:StatusMessage>ErrorCode nr25</saml2p:StatusMessage>
    </saml2p:Status>

as defined: https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/spid_tabella_messaggi_di_anomalia_v1.0.pdf

**Comment by psmiraglia** [comment]
As in the documentation, Shibboleth SP already supports errors management

https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPErrors

In case of error, the SP "encodes" the error in a query string as in the following (not normative) example

```
http://example.org/error?now=Tue Jan 31 11:32:41 2012
    &requestURL=https://example.org/Shibboleth.sso/SAML2/POST
    &errorType=opensaml::FatalProfileException
    &errorText=SAML response contained an error.
    &RelayState=https://example.org/secure/getattrs
    &entityID=urn:mace:incommon:idp.protectnetwork.org
    &statusCode=urn:oasis:names:tc:SAML:2.0:status:Responder
    &statusCode2=urn:oasis:names:tc:SAML:2.0:status:AuthnFailed
```

The `GET` destination endpoint can be configured in `shibboleth.xml` as follows

```.xml
...
<Errors supportContact="help@example.org" redirectErrors="http://example.org/error" />
...
```

The end-user is in charge to implement his own error management page according to the needs. For instance

https://github.com/italia/spid-auth-docker/blob/65a7a257c4f487f538d238c3bdb333d22e5030d0/example/index.js#L83-L95
